
http://localhost:3001/api/persons/6api/persons/624c27fb97c976b75aced54e
###

PUT http://localhost:3001/api/persons/api/persons/624c27fb97c976b75aced54e HTTP/1.1
content-type: application/json

{
    "name": "Mike Hammer44",
    "number": "234234234"
}

###
http://localhost:3001/api/persons


http://localhost:3005/

###
https://part3-helsinki-backend.herokuapp.com/info
###
https://part3-helsinki-backend.herokuapp.com/api/persons/
###
https://part3-helsinki-backend.herokuapp.com/api/persons/23
###
DELETE https://part3-helsinki-backend.herokuapp.com/api/persons/2


###
POST https://part3-helsinki-backend.herokuapp.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Mike Hammer44",
    "number": "234234234"
}

#####
http://localhost:3005/api/persons/
###
http://localhost:3005/api/persons/23
###
DELETE http://localhost:3005/api/persons/2


###
POST http://localhost:3005/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Mike Hammer44",
    "number": "234234234"
}
https://part3-helsinki-backend.herokuapp.com/