http://localhost:3001/

###
http://localhost:3001/info
###
http://localhost:3001/api/persons/
###
http://localhost:3001/api/persons/2
###
DELETE http://localhost:3001/api/persons/2


###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Mike Hammer",
    "number": "3434-2323T"
}